name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: DockerLogin
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build -t qinbatista/ipreporter${{ vars.CLIENT_DOMAIN_NAME }} .  --build-arg google_username="${{ secrets.GOOGLE_USERNAME }}" --build-arg google_password="${{ secrets.GOOGLE_PASSWORD }}" --build-arg client_domain_name="${{ vars.CLIENT_DOMAIN_NAME }}" --build-arg server_domain_name="${{ vars.SERVER_DOMAIN_NAME }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push
        run: docker push qinbatista/ipreporter${{ vars.CLIENT_DOMAIN_NAME }}

  buildOther:
    runs-on: ubuntu-latest
    environment: CQ
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build -t qinbatista/ipreporter${{ vars.CLIENT_DOMAIN_NAME }} .  --build-arg google_username="${{ secrets.GOOGLE_USERNAME }}" --build-arg google_password="${{ secrets.GOOGLE_PASSWORD }}" --build-arg client_domain_name="${{ vars.CLIENT_DOMAIN_NAME }}" --build-arg server_domain_name="${{ vars.SERVER_DOMAIN_NAME }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push
        run: docker push qinbatista/ipreporter${{ vars.CLIENT_DOMAIN_NAME }}