name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build_cq_qinyupeng_com:
    runs-on: ubuntu-latest
    environment: CQ
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build -t qinbatista/ipreporter${{ vars.CQ_CLIENT }} .
            --build-arg google_username="${{ secrets.GOOGLE_USERNAME }}"
            --build-arg google_password="${{ secrets.GOOGLE_PASSWORD }}"
            --build-arg client_domain_name="${{ vars.CQ_CLIENT }}"
            --build-arg server_domain_name="${{ vars.SERVER_DOMAIN_NAME }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push
        run: docker push qinbatista/ipreporter${{ vars.CQ_CLIENT }}

  build_cq_qinbatista_com_test:
    runs-on: ubuntu-latest
    environment: CQ
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build -t qinbatista/ipreportertest${{ vars.SEVER_DOMAIN_NAME_TIMOV4 }} .
            --build-arg google_username="${{ secrets.GOOGLE_USERNAME }}"
            --build-arg google_password="${{ secrets.GOOGLE_PASSWORD }}"
            --build-arg client_domain_name="${{ vars.CQ_CLIENT }}"
            --build-arg server_domain_name="${{ vars.SEVER_DOMAIN_NAME_TIMOV4 }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push
        run: docker push qinbatista/ipreportertest${{ vars.SEVER_DOMAIN_NAME_TIMOV4 }}